— - USUARIO: PEPTIO
— - PASSWORD:qq
CREATE LOGIN pepito WITH PASSWORD='qq',
	DEFAULT_DATABASE=ejemplo
USE ejemplo
CREATE USER pepito FOR LOGIN pepito
GRANT EXECUTE, INSERT, UPDATE, DELETE, 
	SELECT TO PEPITO